environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python36-x64"

install:
  - cmd: "%PYTHON%\\python.exe -m pip install keyring requests requests-mock pytest pylint==1.9.3 astroid==1.6.5 flask==1.1.1 werkzeug==0.15.5"

build: off

test_script:
  - cmd: "%PYTHON%\\Scripts\\pylint.exe stbt_rig.py"
  - cmd: "%PYTHON%\\Scripts\\pytest.exe -vv"
