environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python36-x64"

install:
  - cmd: "%PYTHON%\\python.exe -m pip install -r requirements.txt"

build: off

test_script:
  - cmd: "%PYTHON%\\Scripts\\pylint.exe stbt_rig.py"
  - cmd: "%PYTHON%\\Scripts\\pytest.exe -vv"
