install:
  - cmd: python.exe -m pip install keyring requests requests-mock pytest pylint==1.9.3 astroid==1.6.5 flask==1.0.2 werkzeug==0.14.1

build: off

test_script:
  - cmd: pylint stbt_rig.py
  - cmd: py.test -vv
