language: python
python:
- '2.7'
- '3.6'

install:
- cat /etc/os-release
- pip install keyring requests requests-mock pytest pylint==1.9.3 astroid==1.6.5 flask==1.1.1 werkzeug==0.15.5

script:
- pylint stbt_rig.py
- pytest -vv
